### ISSUE TITLE
Failure occurred in prepare()

### ISSUE THREAD

**Issue by yaomtc** [chaotic-aur/pkgbuild-extra-cmake-modules-git#1]
Terminal output:

```
$ makepkg
==> Making package: extra-cmake-modules-git 5.84.0_r3332.g462fe7f-1 (Tue 02 Nov 2021 04:31:51 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning extra-cmake-modules git repo...
Cloning into bare repository '/home/chris/Software/pkgbuild-extra-cmake-modules-git-master/extra-cmake-modules'...
remote: Enumerating objects: 16234, done.
remote: Counting objects: 100% (918/918), done.
remote: Compressing objects: 100% (635/635), done.
remote: Total 16234 (delta 508), reused 654 (delta 279), pack-reused 15316
Receiving objects: 100% (16234/16234), 3.27 MiB | 15.81 MiB/s, done.
Resolving deltas: 100% (10597/10597), done.
  -> Found ECM-no-init.py.patch
  -> Found Py2-no-sip.patch
==> Validating source files with sha256sums...
    extra-cmake-modules ... Skipped
    ECM-no-init.py.patch ... Passed
    Py2-no-sip.patch ... Passed
==> Extracting sources...
  -> Creating working copy of extra-cmake-modules git repo...
Cloning into 'extra-cmake-modules'...
done.
==> Starting prepare()...
patching file find-modules/GeneratePythonBindingUmbrellaModule.cmake
patching file find-modules/FindPythonModuleGeneration.cmake
Hunk #1 FAILED at 255.
1 out of 1 hunk FAILED -- saving rejects to file find-modules/FindPythonModuleGeneration.cmake.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by PedroHLC** [comment]
@IslandC0der the patch is outdated, can you fix it? Or maybe @dr460nf1r3?

**Comment by IslandC0der** [comment]
> @IslandC0der the patch is outdated, can you fix it? Or maybe @dr460nf1r3?

Will do :)

**Comment by dr460nf1r3** [comment]
The issue is solved, I was able to build the package. Thanks @IslandC0der! :)

**Comment by yaomtc** [comment]
Nothing has changed, it still doesn't build for me with the PKGBUILD on this repo.

**Comment by dr460nf1r3** [comment]
What's the actual log tho? Since I built it today, it's definitely working 👀

**Comment by IslandC0der** [comment]
The patch has served its purpose, we don't need it anymore :)
I've just removed it.

**Comment by yaomtc** [comment]
@dr460nf1r3 Actual log? There's more than just the terminal output that I posted? I don't see anything in the journal about it, and setting the -L option for makepkg logging just results in a file with an excerpt of the aforementioned terminal output...

```
patching file find-modules/GeneratePythonBindingUmbrellaModule.cmake
patching file find-modules/FindPythonModuleGeneration.cmake
Hunk #1 FAILED at 255.
1 out of 1 hunk FAILED -- saving rejects to file find-modules/FindPythonModuleGeneration.cmake.rej
^[[1m^[[31m==> ERROR:^[(B^[[m^[[1m A failure occurred in prepare().^[(B^[[m
^[[1m    Aborting...^[(B^[[m
```

**Comment by yaomtc** [comment]
After extracting the updated ZIP, I now get a different error:

```
$ makepkg
==> Making package: extra-cmake-modules-git 5.87.0_r3368.gdc86450-1 (Sat 06 Nov 2021 02:14:21 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning extra-cmake-modules git repo...
Cloning into bare repository '/home/chris/Software/pkgbuild-extra-cmake-modules-git-master/extra-cmake-modules'...
remote: Enumerating objects: 16234, done.
remote: Counting objects: 100% (918/918), done.
remote: Compressing objects: 100% (635/635), done.
remote: Total 16234 (delta 508), reused 654 (delta 279), pack-reused 15316
Receiving objects: 100% (16234/16234), 3.27 MiB | 15.96 MiB/s, done.
Resolving deltas: 100% (10597/10597), done.
  -> Found ECM-no-init.py.patch
==> ERROR: Py2-no-sip.patch was not found in the build directory and is not a URL.
```

**Comment by PedroHLC** [comment]
(Just following up to be sure)
@yaomtc did you try with the latest commit?

**Comment by yaomtc** [comment]
Now it works, thank you!
